index:
    path: /
    controller: App\Controller\BlogController::renderIndexPage
news-page:
    path: /newspaper
    controller: App\Controller\BlogController::renderNewsPage
feedback-page:
    path: /message
    controller: App\Controller\BlogController::renderFeedbackPage
about-page:
    path: /about
    controller: App\Controller\BlogController::renderAboutPage
contact-page:
    path: /contact
    controller: App\Controller\BlogController::renderContactPage
entry-creator:
    path: /new-entry
    controller: App\Controller\NewPostController::new